#!/usr/bin/env bash
# Host INPUT filter via dedicated nftables table (Docker-safe: no full flush).

module_firewall() {
  if [[ "${FIREWALL_ENABLE}" != "1" ]]; then
    log "module: firewall (skipped)"
    return 0
  fi
  log "module: firewall"

  pacman_install nftables

  local nft_dest=/etc/nftables.d/arch-rails-server.nft
  install -d /etc/nftables.d
  render_nftables_ruleset >"${nft_dest}"
  chmod 0644 "${nft_dest}"
  log "wrote ${nft_dest}"

  write_nftables_loader

  if nft -f "${nft_dest}"; then
    log "nftables table arch_rails_server applied"
  else
    die "failed to apply ${nft_dest}"
  fi

  systemctl enable nftables.service 2>/dev/null || true
  systemctl restart nftables.service 2>/dev/null || {
    warn "nftables.service restart failed; table may still be loaded via nft -f"
  }
}

render_nftables_ruleset() {
  local ports=()
  [[ "${FIREWALL_ALLOW_SSH}" == "1" ]] && ports+=(22)
  [[ "${FIREWALL_ALLOW_HTTP}" == "1" ]] && ports+=(80)
  [[ "${FIREWALL_ALLOW_HTTPS}" == "1" ]] && ports+=(443)

  if [[ -n "${FIREWALL_EXTRA_TCP:-}" ]]; then
    local port
    IFS=',' read -ra extra <<<"${FIREWALL_EXTRA_TCP}"
    for port in "${extra[@]}"; do
      port="$(echo "${port}" | tr -d '[:space:]')"
      [[ -z "${port}" ]] && continue
      ports+=("${port}")
    done
  fi

  cat <<'HDR'
#!/usr/sbin/nft -f
# Generated by arch-rails-server bootstrap — dedicated table (Docker-safe).

destroy table inet arch_rails_server

table inet arch_rails_server {
  chain input {
    type filter hook input priority filter; policy drop;

    ct state invalid drop
    ct state established,related accept
    iif "lo" accept

    ip protocol icmp accept
    ip6 nexthdr icmpv6 accept
HDR

  local p
  for p in "${ports[@]}"; do
    printf '    tcp dport %s accept\n' "${p}"
  done

  cat <<'FTR'
  }
}
FTR
}

write_nftables_loader() {
  local conf=/etc/nftables.conf
  local backup=/etc/nftables.conf.arch-rails-server.bak

  if [[ -f "${conf}" ]] && ! grep -q 'arch-rails-server managed' "${conf}" 2>/dev/null; then
    cp -a "${conf}" "${backup}"
    log "backed up existing ${conf} -> ${backup}"
  fi

  cat >"${conf}" <<'EOF'
#!/usr/sbin/nft -f
# arch-rails-server managed — loads /etc/nftables.d/*.nft
# Does not flush other tables; each drop-in should use its own table name.

include "/etc/nftables.d/*.nft"
EOF
  chmod 0644 "${conf}"
  log "wrote ${conf} loader"
}
